#!/bin/bash

BIN="./uvroff2"
DIFFBIN=/usr/bin/diff
TESTDIR=/home/zastre/seng265/assign2

for i in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20
do

	echo testing input  $i
	$BIN $TESTDIR/in$i.txt | $DIFFBIN $TESTDIR/out$i.txt - 

done
