#!/bin/bash

#gcc -Wall -g -std=c99 uvroff.c -o uvroff

echo "testing in01.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in01.txt > ./out01.txt
diff ~/SENG265/allanliu/a2/tests/out01.txt ./out01.txt

echo "testing in02.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in02.txt > ./out02.txt
diff ~/SENG265/allanliu/a2/tests/out02.txt ./out02.txt

echo "testing in03.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in03.txt > ./out03.txt
diff ~/SENG265/allanliu/a2/tests/out03.txt ./out03.txt

echo "testing in04.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in04.txt > ./out04.txt
diff ~/SENG265/allanliu/a2/tests/out04.txt ./out04.txt

echo "testing in05.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in05.txt > ./out05.txt
diff ~/SENG265/allanliu/a2/tests/out05.txt ./out05.txt

echo "testing in06.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in06.txt > ./out06.txt
diff ~/SENG265/allanliu/a2/tests/out06.txt ./out06.txt

echo "testing in07.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in07.txt > ./out07.txt
diff ~/SENG265/allanliu/a2/tests/out07.txt ./out07.txt

echo "testing in08.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in08.txt > ./out08.txt
diff ~/SENG265/allanliu/a2/tests/out08.txt ./out08.txt

echo "testing in09.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in09.txt > ./out09.txt
diff ~/SENG265/allanliu/a2/tests/out09.txt ./out09.txt

echo "testing in10.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in10.txt > ./out10.txt
diff ~/SENG265/allanliu/a2/tests/out10.txt ./out10.txt

echo "testing in11.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in11.txt > ./out11.txt
diff ~/SENG265/allanliu/a2/tests/out11.txt ./out11.txt

echo "testing in12.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in12.txt > ./out12.txt
diff ~/SENG265/allanliu/a2/tests/out12.txt ./out12.txt

echo "testing in13.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in13.txt > ./out13.txt
diff ~/SENG265/allanliu/a2/tests/out13.txt ./out13.txt

echo "testing in14.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in14.txt > ./out14.txt
diff ~/SENG265/allanliu/a2/tests/out14.txt ./out14.txt

echo "testing in15.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in15.txt > ./out15.txt
diff ~/SENG265/allanliu/a2/tests/out15.txt ./out15.txt

echo "testing in16.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in16.txt > ./out16.txt
diff ~/SENG265/allanliu/a2/tests/out16.txt ./out16.txt

echo "testing in17.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in17.txt > ./out17.txt
diff ~/SENG265/allanliu/a2/tests/out17.txt ./out17.txt

echo "testing in18.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in18.txt > ./out18.txt
diff ~/SENG265/allanliu/a2/tests/out18.txt ./out18.txt

echo "testing in19.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in19.txt > ./out19.txt
diff ~/SENG265/allanliu/a2/tests/out19.txt ./out19.txt

echo "testing in20.txt"
python3 uvroff2.py ~/SENG265/allanliu/a2/tests/in20.txt > ./out20.txt
diff ~/SENG265/allanliu/a2/tests/out20.txt ./out20.txt





