#!/bin/bash

gcc -Wall -g -std=c99 uvroff.c -o uvroff

echo "testing in01.txt"
./uvroff ~/SENG265/allanliu/a1/tests/in01.txt > ./out01.txt
diff ~/SENG265/allanliu/a1/tests/out01.txt ./out01.txt

echo "testing in02.txt"
./uvroff ~/SENG265/allanliu/a1/tests/in02.txt > ./out02.txt
diff ~/SENG265/allanliu/a1/tests/out02.txt ./out02.txt

echo "testing in03.txt"
./uvroff ~/SENG265/allanliu/a1/tests/in03.txt > ./out03.txt
diff ~/SENG265/allanliu/a1/tests/out03.txt ./out03.txt

echo "testing in04.txt"
./uvroff ~/SENG265/allanliu/a1/tests/in04.txt > ./out04.txt
diff ~/SENG265/allanliu/a1/tests/out04.txt ./out04.txt

echo "testing in05.txt"
./uvroff ~/SENG265/allanliu/a1/tests/in05.txt > ./out05.txt
diff ~/SENG265/allanliu/a1/tests/out05.txt ./out05.txt

echo "testing in06.txt"
./uvroff ~/SENG265/allanliu/a1/tests/in06.txt > ./out06.txt
diff ~/SENG265/allanliu/a1/tests/out06.txt ./out06.txt

echo "testing in07.txt"
./uvroff ~/SENG265/allanliu/a1/tests/in07.txt > ./out07.txt
diff ~/SENG265/allanliu/a1/tests/out07.txt ./out07.txt

echo "testing in08.txt"
./uvroff ~/SENG265/allanliu/a1/tests/in08.txt > ./out08.txt
diff ~/SENG265/allanliu/a1/tests/out08.txt ./out08.txt

echo "testing in09.txt"
./uvroff ~/SENG265/allanliu/a1/tests/in09.txt > ./out09.txt
diff ~/SENG265/allanliu/a1/tests/out09.txt ./out09.txt

echo "testing in10.txt"
./uvroff ~/SENG265/allanliu/a1/tests/in10.txt > ./out10.txt
diff ~/SENG265/allanliu/a1/tests/out10.txt ./out10.txt
